apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: andreistefanciprian/gomicropay-email:latest@sha256:e6101f0eb453b08f61c96a4a472ad6d28399d3aeb5c8e250cd47a5f1dd114a13
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: email-secret
            - configMapRef:
                name: email-configmap