apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: andreistefanciprian/gomicropay-email:latest@sha256:80970ce547a6bccab64f2e56d50bccff2337ee7374ddb9850c083f09ee35debc
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: email-secret
            - configMapRef:
                name: email-configmap