apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: andreistefanciprian/gomicropay-email:latest@sha256:9ea3130515f106a0bcc31b75fc22362aaa9ac46eb3a40f323838a71d887e75cc
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: email-secret
            - configMapRef:
                name: email-configmap