apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: money-movement
resources:
  - namespace.yaml
  - money-movement-deploy.yaml
  - configmap.yaml
  - secret.yaml
  - service.yaml
# Add other manifest files in this folder below
