apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-movement
  labels:
    app: money-movement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: money-movement
  template:
    metadata:
      labels:
        app: money-movement
    spec:
      containers:
        - name: money-movement
          image: andreistefanciprian/gomicropay-money-movement:latest@sha256:c00ef6a711d0a5919f199359e7268cd249708e77a4000d1217d79a43ee15bf24
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: money-movement-secret
            - configMapRef:
                name: money-movement-configmap
          ports:
            - containerPort: 7000