apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-movement
  labels:
    app: money-movement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: money-movement
  template:
    metadata:
      labels:
        app: money-movement
    spec:
      containers:
        - name: money-movement
          image: andreistefanciprian/gomicropay-money-movement:latest@sha256:cb6f0fc1d9483aca616b15707dc8916ff23266c29ca713e28f91821546bc02b7
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: money-movement-secret
            - configMapRef:
                name: money-movement-configmap
          ports:
            - containerPort: 7000