// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.4
// source: money_movement/proto/money_movement_svc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletType int32

const (
	WalletType_CUSTOMER WalletType = 0
	WalletType_MERCHANT WalletType = 1
)

// Enum value maps for WalletType.
var (
	WalletType_name = map[int32]string{
		0: "CUSTOMER",
		1: "MERCHANT",
	}
	WalletType_value = map[string]int32{
		"CUSTOMER": 0,
		"MERCHANT": 1,
	}
)

func (x WalletType) Enum() *WalletType {
	p := new(WalletType)
	*p = x
	return p
}

func (x WalletType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletType) Descriptor() protoreflect.EnumDescriptor {
	return file_money_movement_proto_money_movement_svc_proto_enumTypes[0].Descriptor()
}

func (WalletType) Type() protoreflect.EnumType {
	return &file_money_movement_proto_money_movement_svc_proto_enumTypes[0]
}

func (x WalletType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletType.Descriptor instead.
func (WalletType) EnumDescriptor() ([]byte, []int) {
	return file_money_movement_proto_money_movement_svc_proto_rawDescGZIP(), []int{0}
}

type AuthorizePayload struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CustomerWalletUserId string                 `protobuf:"bytes,1,opt,name=customerWalletUserId,proto3" json:"customerWalletUserId,omitempty"`
	MerchantWalletUserId string                 `protobuf:"bytes,2,opt,name=merchantWalletUserId,proto3" json:"merchantWalletUserId,omitempty"`
	Cents                int64                  `protobuf:"varint,3,opt,name=cents,proto3" json:"cents,omitempty"`
	Currency             string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthorizePayload) Reset() {
	*x = AuthorizePayload{}
	mi := &file_money_movement_proto_money_movement_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePayload) ProtoMessage() {}

func (x *AuthorizePayload) ProtoReflect() protoreflect.Message {
	mi := &file_money_movement_proto_money_movement_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePayload.ProtoReflect.Descriptor instead.
func (*AuthorizePayload) Descriptor() ([]byte, []int) {
	return file_money_movement_proto_money_movement_svc_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizePayload) GetCustomerWalletUserId() string {
	if x != nil {
		return x.CustomerWalletUserId
	}
	return ""
}

func (x *AuthorizePayload) GetMerchantWalletUserId() string {
	if x != nil {
		return x.MerchantWalletUserId
	}
	return ""
}

func (x *AuthorizePayload) GetCents() int64 {
	if x != nil {
		return x.Cents
	}
	return 0
}

func (x *AuthorizePayload) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CapturePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapturePayload) Reset() {
	*x = CapturePayload{}
	mi := &file_money_movement_proto_money_movement_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapturePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturePayload) ProtoMessage() {}

func (x *CapturePayload) ProtoReflect() protoreflect.Message {
	mi := &file_money_movement_proto_money_movement_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturePayload.ProtoReflect.Descriptor instead.
func (*CapturePayload) Descriptor() ([]byte, []int) {
	return file_money_movement_proto_money_movement_svc_proto_rawDescGZIP(), []int{1}
}

func (x *CapturePayload) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_money_movement_proto_money_movement_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_money_movement_proto_money_movement_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_money_movement_proto_money_movement_svc_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeResponse) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

type CheckBalancePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBalancePayload) Reset() {
	*x = CheckBalancePayload{}
	mi := &file_money_movement_proto_money_movement_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBalancePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBalancePayload) ProtoMessage() {}

func (x *CheckBalancePayload) ProtoReflect() protoreflect.Message {
	mi := &file_money_movement_proto_money_movement_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBalancePayload.ProtoReflect.Descriptor instead.
func (*CheckBalancePayload) Descriptor() ([]byte, []int) {
	return file_money_movement_proto_money_movement_svc_proto_rawDescGZIP(), []int{3}
}

func (x *CheckBalancePayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BalanceCents  int64                  `protobuf:"varint,1,opt,name=balanceCents,proto3" json:"balanceCents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBalanceResponse) Reset() {
	*x = CheckBalanceResponse{}
	mi := &file_money_movement_proto_money_movement_svc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBalanceResponse) ProtoMessage() {}

func (x *CheckBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_money_movement_proto_money_movement_svc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBalanceResponse.ProtoReflect.Descriptor instead.
func (*CheckBalanceResponse) Descriptor() ([]byte, []int) {
	return file_money_movement_proto_money_movement_svc_proto_rawDescGZIP(), []int{4}
}

func (x *CheckBalanceResponse) GetBalanceCents() int64 {
	if x != nil {
		return x.BalanceCents
	}
	return 0
}

type CreateAccountPayload struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EmailAddress           string                 `protobuf:"bytes,1,opt,name=emailAddress,proto3" json:"emailAddress,omitempty"`
	WalletType             WalletType             `protobuf:"varint,2,opt,name=walletType,proto3,enum=WalletType" json:"walletType,omitempty"`
	InitialBalanceCurrency string                 `protobuf:"bytes,3,opt,name=initialBalanceCurrency,proto3" json:"initialBalanceCurrency,omitempty"`
	InitialBalanceCents    int64                  `protobuf:"varint,4,opt,name=initialBalanceCents,proto3" json:"initialBalanceCents,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateAccountPayload) Reset() {
	*x = CreateAccountPayload{}
	mi := &file_money_movement_proto_money_movement_svc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountPayload) ProtoMessage() {}

func (x *CreateAccountPayload) ProtoReflect() protoreflect.Message {
	mi := &file_money_movement_proto_money_movement_svc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountPayload.ProtoReflect.Descriptor instead.
func (*CreateAccountPayload) Descriptor() ([]byte, []int) {
	return file_money_movement_proto_money_movement_svc_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccountPayload) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *CreateAccountPayload) GetWalletType() WalletType {
	if x != nil {
		return x.WalletType
	}
	return WalletType_CUSTOMER
}

func (x *CreateAccountPayload) GetInitialBalanceCurrency() string {
	if x != nil {
		return x.InitialBalanceCurrency
	}
	return ""
}

func (x *CreateAccountPayload) GetInitialBalanceCents() int64 {
	if x != nil {
		return x.InitialBalanceCents
	}
	return 0
}

var File_money_movement_proto_money_movement_svc_proto protoreflect.FileDescriptor

const file_money_movement_proto_money_movement_svc_proto_rawDesc = "" +
	"\n" +
	"-money_movement/proto/money_movement_svc.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xac\x01\n" +
	"\x10AuthorizePayload\x122\n" +
	"\x14customerWalletUserId\x18\x01 \x01(\tR\x14customerWalletUserId\x122\n" +
	"\x14merchantWalletUserId\x18\x02 \x01(\tR\x14merchantWalletUserId\x12\x14\n" +
	"\x05cents\x18\x03 \x01(\x03R\x05cents\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\"\n" +
	"\x0eCapturePayload\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid\"%\n" +
	"\x11AuthorizeResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid\"-\n" +
	"\x13CheckBalancePayload\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\":\n" +
	"\x14CheckBalanceResponse\x12\"\n" +
	"\fbalanceCents\x18\x01 \x01(\x03R\fbalanceCents\"\xd1\x01\n" +
	"\x14CreateAccountPayload\x12\"\n" +
	"\femailAddress\x18\x01 \x01(\tR\femailAddress\x12+\n" +
	"\n" +
	"walletType\x18\x02 \x01(\x0e2\v.WalletTypeR\n" +
	"walletType\x126\n" +
	"\x16initialBalanceCurrency\x18\x03 \x01(\tR\x16initialBalanceCurrency\x120\n" +
	"\x13initialBalanceCents\x18\x04 \x01(\x03R\x13initialBalanceCents*(\n" +
	"\n" +
	"WalletType\x12\f\n" +
	"\bCUSTOMER\x10\x00\x12\f\n" +
	"\bMERCHANT\x10\x012\xfb\x01\n" +
	"\x14MoneyMovementService\x122\n" +
	"\tAuthorize\x12\x11.AuthorizePayload\x1a\x12.AuthorizeResponse\x122\n" +
	"\aCapture\x12\x0f.CapturePayload\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\fCheckBalance\x12\x14.CheckBalancePayload\x1a\x15.CheckBalanceResponse\x12>\n" +
	"\rCreateAccount\x12\x15.CreateAccountPayload\x1a\x16.google.protobuf.EmptyBCZAgithub.com/andreistefanciprian/gomicropay/money_movement/proto/pbb\x06proto3"

var (
	file_money_movement_proto_money_movement_svc_proto_rawDescOnce sync.Once
	file_money_movement_proto_money_movement_svc_proto_rawDescData []byte
)

func file_money_movement_proto_money_movement_svc_proto_rawDescGZIP() []byte {
	file_money_movement_proto_money_movement_svc_proto_rawDescOnce.Do(func() {
		file_money_movement_proto_money_movement_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_money_movement_proto_money_movement_svc_proto_rawDesc), len(file_money_movement_proto_money_movement_svc_proto_rawDesc)))
	})
	return file_money_movement_proto_money_movement_svc_proto_rawDescData
}

var file_money_movement_proto_money_movement_svc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_money_movement_proto_money_movement_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_money_movement_proto_money_movement_svc_proto_goTypes = []any{
	(WalletType)(0),              // 0: WalletType
	(*AuthorizePayload)(nil),     // 1: AuthorizePayload
	(*CapturePayload)(nil),       // 2: CapturePayload
	(*AuthorizeResponse)(nil),    // 3: AuthorizeResponse
	(*CheckBalancePayload)(nil),  // 4: CheckBalancePayload
	(*CheckBalanceResponse)(nil), // 5: CheckBalanceResponse
	(*CreateAccountPayload)(nil), // 6: CreateAccountPayload
	(*emptypb.Empty)(nil),        // 7: google.protobuf.Empty
}
var file_money_movement_proto_money_movement_svc_proto_depIdxs = []int32{
	0, // 0: CreateAccountPayload.walletType:type_name -> WalletType
	1, // 1: MoneyMovementService.Authorize:input_type -> AuthorizePayload
	2, // 2: MoneyMovementService.Capture:input_type -> CapturePayload
	4, // 3: MoneyMovementService.CheckBalance:input_type -> CheckBalancePayload
	6, // 4: MoneyMovementService.CreateAccount:input_type -> CreateAccountPayload
	3, // 5: MoneyMovementService.Authorize:output_type -> AuthorizeResponse
	7, // 6: MoneyMovementService.Capture:output_type -> google.protobuf.Empty
	5, // 7: MoneyMovementService.CheckBalance:output_type -> CheckBalanceResponse
	7, // 8: MoneyMovementService.CreateAccount:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_money_movement_proto_money_movement_svc_proto_init() }
func file_money_movement_proto_money_movement_svc_proto_init() {
	if File_money_movement_proto_money_movement_svc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_money_movement_proto_money_movement_svc_proto_rawDesc), len(file_money_movement_proto_money_movement_svc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_money_movement_proto_money_movement_svc_proto_goTypes,
		DependencyIndexes: file_money_movement_proto_money_movement_svc_proto_depIdxs,
		EnumInfos:         file_money_movement_proto_money_movement_svc_proto_enumTypes,
		MessageInfos:      file_money_movement_proto_money_movement_svc_proto_msgTypes,
	}.Build()
	File_money_movement_proto_money_movement_svc_proto = out.File
	file_money_movement_proto_money_movement_svc_proto_goTypes = nil
	file_money_movement_proto_money_movement_svc_proto_depIdxs = nil
}
