apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: andreistefanciprian/gomicropay-auth:latest@sha256:50c6fae72336339a99d01ef8197ae1535164e0615a744d0f6f67a4e6d3bcfe00
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: auth-secret
            - configMapRef:
                name: auth-configmap
          ports:
            - containerPort: 9000