apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  MYSQL_PASSWORD: "Auth123"
  MYSQL_USER: "auth_user"
  MYSQL_DB: "auth"
  MYSQL_HOST: "mysql-auth.auth.svc.cluster.local"
  MYSQL_PORT: "3306"