apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger
  labels:
    app: ledger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger
  template:
    metadata:
      labels:
        app: ledger
    spec:
      containers:
        - name: ledger
          image: andreistefanciprian/gomicropay-ledger:latest@sha256:5cbe5219ce9f4b1792bfe60749a56bdfd55c154e6be2c067882cb3547c9f66b8
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ledger-secret
            - configMapRef:
                name: ledger-configmap