apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger
  labels:
    app: ledger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger
  template:
    metadata:
      labels:
        app: ledger
    spec:
      containers:
        - name: ledger
          image: andreistefanciprian/gomicropay-ledger:latest@sha256:9c352651abf59650754ed3ba6ac5d97ca8e24d9f19f78984535fa303b5248f81
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ledger-secret
            - configMapRef:
                name: ledger-configmap