apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger
  labels:
    app: ledger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger
  template:
    metadata:
      labels:
        app: ledger
    spec:
      containers:
        - name: ledger
          image: andreistefanciprian/gomicropay-ledger:latest@sha256:f55365c0753688a1350967201400257e4a6ee555079bb77acf6e78712f1d34a6
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ledger-secret
            - configMapRef:
                name: ledger-configmap