apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: andreistefanciprian/gomicropay-gateway@sha256:4aad4864c0b4b2e76eac6cc527aa4cf7a1538c2dec67d38a0c8e0239fc8e2598
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: gateway-secret
            - configMapRef:
                name: gateway-configmap
          ports:
            - containerPort: 8080