apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: andreistefanciprian/gomicropay-gateway@sha256:d4c655a1f96a8483bb95806a7b0ae7432a61d431a60d7ca3ad607657742643cf
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: gateway-secret
            - configMapRef:
                name: gateway-configmap
          ports:
            - containerPort: 8080