apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api-gateway
resources:
  - gateway-deploy.yaml
  - configmap.yaml
  - ingress.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
