apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: andreistefanciprian/gomicropay-gateway@sha256:aa22cd44fde5b31511b3d5535beb3c0ed00ea2364faa241caf397e0341ec0218
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: gateway-secret
            - configMapRef:
                name: gateway-configmap
          ports:
            - containerPort: 8080