apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  MONEY_MOVEMENT_HOST: "money-movement"
  MONEY_MOVEMENT_PORT: "7000"
  AUTH_HOST: "auth"
  AUTH_PORT: "9000"
  LOG_LEVEL: "DEBUG"