apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    app: mysql-client
spec:
  containers:
    - name: mysql-client
      image: mysql:9.5@sha256:c9f0c66a87356518d4b30dbc065eb4567e4a04aff4d0ff194dea0973e5985b57
      command: ["sleep", "infinity"]
