apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    app: mysql-client
spec:
  containers:
    - name: mysql-client
      image: mysql:9.5@sha256:5ca0a273ed28c73acaef91da8bf1eca3711bee94bce4c378d42846375e645a72
      command: ["sleep", "infinity"]
