apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    app: mysql-client
spec:
  containers:
    - name: mysql-client
      image: mysql:9.7@sha256:30a0abfa7b502a496e12339b54cd07aaa70363396dc4b8e8a72a92804a505cd6
      command: ["sleep", "infinity"]
