// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.4
// source: auth/proto/auth_svc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_auth_proto_auth_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_auth_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_auth_proto_auth_svc_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type UserEmailAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEmailAddress) Reset() {
	*x = UserEmailAddress{}
	mi := &file_auth_proto_auth_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEmailAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEmailAddress) ProtoMessage() {}

func (x *UserEmailAddress) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_auth_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEmailAddress.ProtoReflect.Descriptor instead.
func (*UserEmailAddress) Descriptor() ([]byte, []int) {
	return file_auth_proto_auth_svc_proto_rawDescGZIP(), []int{1}
}

func (x *UserEmailAddress) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type HashedPassword struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HashedPassword string                 `protobuf:"bytes,1,opt,name=hashedPassword,proto3" json:"hashedPassword,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HashedPassword) Reset() {
	*x = HashedPassword{}
	mi := &file_auth_proto_auth_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashedPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashedPassword) ProtoMessage() {}

func (x *HashedPassword) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_auth_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashedPassword.ProtoReflect.Descriptor instead.
func (*HashedPassword) Descriptor() ([]byte, []int) {
	return file_auth_proto_auth_svc_proto_rawDescGZIP(), []int{2}
}

func (x *HashedPassword) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

type UserExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUser        bool                   `protobuf:"varint,1,opt,name=isUser,proto3" json:"isUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExistsResponse) Reset() {
	*x = UserExistsResponse{}
	mi := &file_auth_proto_auth_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistsResponse) ProtoMessage() {}

func (x *UserExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_auth_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExistsResponse.ProtoReflect.Descriptor instead.
func (*UserExistsResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_auth_svc_proto_rawDescGZIP(), []int{3}
}

func (x *UserExistsResponse) GetIsUser() bool {
	if x != nil {
		return x.IsUser
	}
	return false
}

type UserRegistrationForm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,4,opt,name=passwordHash,proto3" json:"passwordHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistrationForm) Reset() {
	*x = UserRegistrationForm{}
	mi := &file_auth_proto_auth_svc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistrationForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistrationForm) ProtoMessage() {}

func (x *UserRegistrationForm) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_auth_svc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistrationForm.ProtoReflect.Descriptor instead.
func (*UserRegistrationForm) Descriptor() ([]byte, []int) {
	return file_auth_proto_auth_svc_proto_rawDescGZIP(), []int{4}
}

func (x *UserRegistrationForm) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserRegistrationForm) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserRegistrationForm) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *UserRegistrationForm) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type UserRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRegistered  bool                   `protobuf:"varint,1,opt,name=isRegistered,proto3" json:"isRegistered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistrationResponse) Reset() {
	*x = UserRegistrationResponse{}
	mi := &file_auth_proto_auth_svc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistrationResponse) ProtoMessage() {}

func (x *UserRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_auth_svc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistrationResponse.ProtoReflect.Descriptor instead.
func (*UserRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_auth_svc_proto_rawDescGZIP(), []int{5}
}

func (x *UserRegistrationResponse) GetIsRegistered() bool {
	if x != nil {
		return x.IsRegistered
	}
	return false
}

var File_auth_proto_auth_svc_proto protoreflect.FileDescriptor

const file_auth_proto_auth_svc_proto_rawDesc = "" +
	"\n" +
	"\x19auth/proto/auth_svc.proto\"\x19\n" +
	"\x05Token\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\"0\n" +
	"\x10UserEmailAddress\x12\x1c\n" +
	"\tuserEmail\x18\x01 \x01(\tR\tuserEmail\"8\n" +
	"\x0eHashedPassword\x12&\n" +
	"\x0ehashedPassword\x18\x01 \x01(\tR\x0ehashedPassword\",\n" +
	"\x12UserExistsResponse\x12\x16\n" +
	"\x06isUser\x18\x01 \x01(\bR\x06isUser\"\x92\x01\n" +
	"\x14UserRegistrationForm\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12\x1c\n" +
	"\tuserEmail\x18\x03 \x01(\tR\tuserEmail\x12\"\n" +
	"\fpasswordHash\x18\x04 \x01(\tR\fpasswordHash\">\n" +
	"\x18UserRegistrationResponse\x12\"\n" +
	"\fisRegistered\x18\x01 \x01(\bR\fisRegistered2\xa8\x02\n" +
	"\vAuthService\x12>\n" +
	"\x16RetrieveHashedPassword\x12\x11.UserEmailAddress\x1a\x0f.HashedPassword\"\x00\x12;\n" +
	"\x0fCheckUserExists\x12\x11.UserEmailAddress\x1a\x13.UserExistsResponse\"\x00\x12B\n" +
	"\fRegisterUser\x12\x15.UserRegistrationForm\x1a\x19.UserRegistrationResponse\"\x00\x12,\n" +
	"\rGenerateToken\x12\x11.UserEmailAddress\x1a\x06.Token\"\x00\x12*\n" +
	"\vVerifyToken\x12\x06.Token\x1a\x11.UserEmailAddress\"\x00B9Z7github.com/andreistefanciprian/gomicropay/auth/proto/pbb\x06proto3"

var (
	file_auth_proto_auth_svc_proto_rawDescOnce sync.Once
	file_auth_proto_auth_svc_proto_rawDescData []byte
)

func file_auth_proto_auth_svc_proto_rawDescGZIP() []byte {
	file_auth_proto_auth_svc_proto_rawDescOnce.Do(func() {
		file_auth_proto_auth_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_auth_svc_proto_rawDesc), len(file_auth_proto_auth_svc_proto_rawDesc)))
	})
	return file_auth_proto_auth_svc_proto_rawDescData
}

var file_auth_proto_auth_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_auth_proto_auth_svc_proto_goTypes = []any{
	(*Token)(nil),                    // 0: Token
	(*UserEmailAddress)(nil),         // 1: UserEmailAddress
	(*HashedPassword)(nil),           // 2: HashedPassword
	(*UserExistsResponse)(nil),       // 3: UserExistsResponse
	(*UserRegistrationForm)(nil),     // 4: UserRegistrationForm
	(*UserRegistrationResponse)(nil), // 5: UserRegistrationResponse
}
var file_auth_proto_auth_svc_proto_depIdxs = []int32{
	1, // 0: AuthService.RetrieveHashedPassword:input_type -> UserEmailAddress
	1, // 1: AuthService.CheckUserExists:input_type -> UserEmailAddress
	4, // 2: AuthService.RegisterUser:input_type -> UserRegistrationForm
	1, // 3: AuthService.GenerateToken:input_type -> UserEmailAddress
	0, // 4: AuthService.VerifyToken:input_type -> Token
	2, // 5: AuthService.RetrieveHashedPassword:output_type -> HashedPassword
	3, // 6: AuthService.CheckUserExists:output_type -> UserExistsResponse
	5, // 7: AuthService.RegisterUser:output_type -> UserRegistrationResponse
	0, // 8: AuthService.GenerateToken:output_type -> Token
	1, // 9: AuthService.VerifyToken:output_type -> UserEmailAddress
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_auth_svc_proto_init() }
func file_auth_proto_auth_svc_proto_init() {
	if File_auth_proto_auth_svc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_auth_svc_proto_rawDesc), len(file_auth_proto_auth_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_auth_svc_proto_goTypes,
		DependencyIndexes: file_auth_proto_auth_svc_proto_depIdxs,
		MessageInfos:      file_auth_proto_auth_svc_proto_msgTypes,
	}.Build()
	File_auth_proto_auth_svc_proto = out.File
	file_auth_proto_auth_svc_proto_goTypes = nil
	file_auth_proto_auth_svc_proto_depIdxs = nil
}
