apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql-deploy.yaml
  - mysql-configmap.yaml
  - mysql-secret.yaml
  - mysql-service.yaml

configMapGenerator:
  - name: mysql-auth-init-sql
    files:
      - init.sql
