apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: andreistefanciprian/gomicropay-payments:latest@sha256:6c674317b95d908e39c5393051a980b10ad2c8224a691fc4b7145da71bf13b5c
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: payments-secret
            - configMapRef:
                name: payments-configmap
          ports:
            - containerPort: 7000