apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: andreistefanciprian/gomicropay-payments:latest@sha256:a51b01172ce680b650ffa3e3cfde059381749dbfb5cfbc8d821943390bc97324
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: payments-secret
            - configMapRef:
                name: payments-configmap
          ports:
            - containerPort: 7000