apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
type: Opaque
stringData:
  MYSQL_PASSWORD: "Auth123"
  MYSQL_USER: "payments_user"
  MYSQL_DB: "payments"
  MYSQL_HOST: "mysql-payments.payments.svc.cluster.local"
  MYSQL_PORT: "3306"