apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-money-movement
  labels:
    app: mysql-money-movement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-money-movement
  template:
    metadata:
      labels:
        app: mysql-money-movement
    spec:
      containers:
        - name: mysql-money-movement
          image: mysql:5.7@sha256:4bc6bc963e6d8443453676cae56536f4b8156d78bae03c0145cbe47c2aad73bb
          envFrom:
            - secretRef:
                name: mysql-money-movement-secret
            - configMapRef:
                name: mysql-money-movement-configmap
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          securityContext:
            privileged: true
          ports:
            - containerPort: 3306
      volumes:
        - name: init-sql
          configMap:
            name: mysql-money-movement-init-sql
            items:
              - key: init.sql
                path: init.sql